language: android
jdk:
  - oraclejdk8
android:
  components:
    - build-tools-23.0.0
    - android-23
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
script:
  - cd ncmb-core
  - ./gradlew build test --continue --info
