language: android
jdk:
  - oraclejdk8
env:
  matrix:
    - ANDROID_SDKS=android-14,sysimg-14  ANDROID_TARGET=android-14  ANDROID_ABI=armeabi-v7a
    - ANDROID_SDKS=android-23,sysimg-23  ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a
android:
  components:
    - build-tools-23.0.0
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
script:
  - cd ncmb-core
  - ./gradlew build test --continue --info
