name: Android

on: [push, pull_request]

env:
  MAVEN_USERNAME: ${{ secrets.OSSRHUSERNAME }}
  MAVEN_PASSWORD: ${{ secrets.OSSRHPASSWORD }}
  GPG_PRIVATE_KEY: ${{ secrets.GPG_SECRET_KEY }}
  PASSPHRASE: ${{ secrets.GPG_PASSWORD }}


jobs:
  build_and_test:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - uses: gradle/gradle-build-action@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: build and test
      run: ./gradlew build test --continue --info

    - name: Publish to Nexus repository
      uses: gradle/gradle-build-action@v2
      with:
        arguments: publish      
