name: Android

on: [push, pull_request]

env:
  MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
  GPG_PRIVATE_KEY: ${{ secrets.SIGNING_GNUPG_SECRETKEY }}
  GPG_PASSPHRASE: ${{ secrets.SIGNING_GNUPG_PASSWORD }}


jobs:
  build_and_test:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.SIGNING_GNUPG_SECRETKEY }}.keys[0]
        passphrase: ${{ secrets.SIGNING_GNUPG_PASSWORD }}
    - name: List Keys
      run: gpg -K
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: GPG_PRIVATE_KEY
        gpg-passphrase: GPG_PASSPHRASE
    - name: build and test
      run: ./gradlew build test --continue --info

    - name: Publish to Nexus repository
      uses: gradle/gradle-build-action@v2
      with:
        arguments: publish      
