name: Android

on: [push, pull_request]

env:
  secret_ossrhUsername: ${{secrets.ossrhUsername}}
  secret_ossrhPassword: ${{secrets.ossrhPassword}}


jobs:
  build_and_test:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: build and test
      run: ./gradlew build test --continue --info
