name: Android

on: [push, pull_request]

env:
  MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

jobs:
  build_and_test:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: ossrh
        server-username: ${{ secrets.OSSRH_USERNAME }}
        server-password: ${{ secrets.OSSRH_TOKEN }}
        gpg-private-key: ${{ secrets.SIGNING_GNUPG_SECRETKEY }}
        gpg-passphrase: ${{ secrets.SIGNING_GNUPG_PASSWORD }}
    - name: Publish to Nexus repository
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/
        username: ${{ secrets.OSSRH_USERNAME }}
        password: ${{ secrets.OSSRH_TOKEN }}
        format: maven2
        repository: ncmb_android
        coordinates: groupId=com.nifcloud.mbaas
        assets: extension=jar
        filename: ../ncmb_android